- name: Installing and configuring a Docker server
  vars_files:
    - [ "group_vars/secrets.yml", "group_vars/all.yml" ]
  hosts: all
  sudo: yes
  roles:
    - docker-patch
    - fretscha.first-five-minutes
    - angstwad.docker_ubuntu
    - aws-cli
