# vi: set sw=2 ts=2:

- name: Deploy and start base docker images
  hosts: all
  vars_files:
    - [ "vars/secrets.yml", "vars/all.yml" ]
  tasks:
    - name: Pull postgres from registry and start container
      register: start_postgresql
      docker:
        name: db
        image: postgres
        state: started
        restart_policy: always
        volumes:
          - "{{ home_dir }}/var/lib/postgresql/data:/var/lib/postgresql/data:rw"

    - name: Create nginx conf directory
      file: path="{{ home_dir }}/var/nginx/conf" state=directory
            owner={{ deploy_user }} group={{ deploy_user }}

    - name: Upload nginx config
      template: src=files/nginx.conf dest="{{ home_dir }}/var/nginx/conf/nginx.conf"
                owner={{ deploy_user }} group={{ deploy_user }}
