# Local/Dev
db:
    image: postgres
    restart: always
    #volumes:
        #- ./docker/var/lib/postgresql/data:/var/lib/postgresql/data:rw

web:
    build: ./src
    volumes:
        - ./src:/app
    ports:
        - "8080:8080"
    links:
        - db
    environment:
        RUNSERVER: 1
