# Prod
db:
    image: postgres
    restart: always
    volumes:
        - /home/vagrant/var/lib/postgresql/data:/var/lib/postgresql/data:rw
    env_file:
        - docker-compose-config/db.env
    #environment:
        #POSTGRES_PASSWORD:
        #POSTGRES_USER:
        #POSTGRES_DB:

nginx:
    image: nginx
    links:
        - web:web
    restart: always
    ports:
        - "80:80"
    volumes:
        - /home/vagrant/var/nginx/conf:/etc/nginx:ro

web:
    image: 242868218257.dkr.ecr.us-east-1.amazonaws.com/django-test:latest
    ports:
        - "8080"
    links:
        - db
    volumes:
        #- /home/vagrant/var/web/.env:/app/.env:ro
        - /home/vagrant/var/web/uwsgi.log:/app/uwsgi.log:rw
    env_file:
        - docker-compose-config/web.env
