# vi: set sw=2 ts=2:

- name: Transfer image from local to remote host
  hosts: all
  vars_files:
    - [ "vars/secrets.yml", "vars/all.yml" ]
  tasks:
    - name: Retrive app version from app image dockerfile
      shell: 'cat {{ image_dir }}/Dockerfile | grep -e "^LABEL.version" | cut -d \" -f 2'
      register: deploy_version
      connection: local

    - name: Build docker app image
      shell: 'docker build -t {{ image_repository }}:{{ deploy_version.stdout }} {{ image_dir }}'
      connection: local

    - name: Save docker app image
      shell: "docker save {{ image_repository }}:{{ deploy_version.stdout }} > /tmp/docker_image.tar"
      connection: local

    - name: Copies docker app image to machine
      copy: src=/tmp/docker_image.tar dest=/tmp/docker_image.tar

    - name: Load docker image
      shell: "docker load < /tmp/docker_image.tar"

    - name: Remove old running app container
      docker:
        name: web
        image: "{{ image_repository }}:latest"
        state: absent

    - name: Remove previous app docker image
      shell: "docker rmi {{ image_repository }}:latest"
      ignore_errors: yes

    - name: Duplicate deploy app image and tag it latest
      shell: "docker tag {{ image_repository }}:{{ deploy_version.stdout }} {{ image_repository}}:latest"

    - name: Remove older releases of app image
      shell: "docker images | grep {{ image_repository }} | grep -v latest | awk '{print \"{{ image_repository }}:\"$2}' | tail -n +4 | xargs -n 1 docker rmi"
      ignore_errors: yes

    - name: Remove local app image export
      shell: "rm /tmp/docker_image.tar"
      connection: local

    - name: Remove remote app image export
      shell: "rm /tmp/docker_image.tar"

    - name: Start app container
      docker:
        name: web
        image: "{{ image_repository }}:latest"
        state: started
        restart_policy: always
        links:
          - db
        ports:
          - "8080"

    - name: Start nginx container
      docker:
        name: nginx
        image: nginx
        state: started
        links:
          - web:web
        ports:
        volumes:
          - "{{ home_dir }}/var/nginx/conf:/etc/nginx:ro"
        ports:
          - "80:80"
