db:
    image: postgres
    restart: always
    volumes:
        - /var/lib/postgresql/data:/home/vagrant/var/lib/postgresql/data:rw

nginx:
    image: nginx
    links:
        - web:web
    restart: always
    ports:
        - "80:80"
    volumes:
        - /etc/nginx:/home/vagrant/var/nginx/conf:ro

web:
    image: 242868218257.dkr.ecr.us-east-1.amazonaws.com/django-test:latest
    ports:
        - "8080"
    links:
        - db
